FROM alpine:latest

WORKDIR /app

# RUN apk add g++ bind-tools make cmake git
RUN apk add --no-cache \
    python3 \
    python3-dev

COPY gcs/ /app/

# RUN cmake .

# RUN make

EXPOSE 65456

CMD ["python3", "main.py"]