FROM alpine:latest

WORKDIR /app

COPY drone /app

RUN apk add g++ make cmake protobuf protobuf-dev gtest-dev
    
RUN cmake .

RUN make

# RUN g++ -o drone drone.cpp drone_test.cpp
RUN g++ -o drone drone.cpp

EXPOSE 65456

CMD ["./drone"]