FROM alpine:latest

WORKDIR /app

RUN apk add --no-cache \
    g++ \
    bind-tools \
    make \
    cmake \
    protobuf \
    protobuf-dev \
    git \
    openssl-dev \
    python3 \
    py3-pip 

RUN python3 -m venv /app/venv
ENV PATH="/app/venv/bin:$PATH"

RUN pip3 install flask

COPY drone/*.cpp drone/*.hpp drone/CMakeLists.txt drone/initScript.py /app/
COPY drone/network_adapters/* /app/network_adapters/

RUN cmake .
RUN make

EXPOSE 65456

CMD ["python3", "initScript.py"]